### ISSUE TITLE
Add support to new flag ignoreDeprecationWarning from esri-leaflet > v3.0.2

### ISSUE THREAD

**Issue by alessandro-lenzi** [slutske22/react-esri-leaflet#14]
Added a deprecation warning when using L.esri.BasemapLayer ([info](https://esri.github.io/esri-leaflet/api-reference/layers/basemap-layer.html)). 
This warning can be disabled by setting the ignoreDeprecationWarning option to true. (https://github.com/Esri/esri-leaflet/pull/1293).

I think it would be interesting to forward that flag on react-esri-leaflet.

**Comment by slutske22** [comment]
I haven't had a chance to see what's new in the new patch of esri-leaflet or esri-leaflet-geocoder, or how its going to affect this wrapper.  I'll take a look when I get a chance.

**Comment by alessandro-lenzi** [comment]
Thank you @slutske22

**Comment by slutske22** [comment]
This is implemented in version 2, which is currently in a @next version.  You can try it out here: https://www.npmjs.com/package/react-esri-leaflet/v/2.0.0, `npm i react-esri-leaflet@next`, Will publish as official version soon.

**Comment by bobmoretti** [comment]
Sorry for the dumb question, but how do I use this option? I'm using `react-esri-leaflet` version 2.0.1.

Inside a `MapContainer` my code instantiates a `BasemapLayer` as follows
```typescript
<BasemapLayer key={mapType} name={mapType}  />
```

**Comment by slutske22** [comment]
> Sorry for the dumb question, but how do I use this option? I'm using `react-esri-leaflet` version 2.0.1.
> 
> Inside a `MapContainer` my code instantiates a `BasemapLayer` as follows
> 
> ```ts
> <BasemapLayer key={mapType} name={mapType}  />
> ```

That code should work fine...is there an issue?  It should just give you fancy intellisense for the fact that the underlying L.esri.basemapLayer is deprecated.

**Comment by bobmoretti** [comment]
Sorry, I did a poor job of explaining my question.

How do I enable the `ignoreDeprecationWarning` option that is in esri-leaflet? Is it a prop for `BasemapLayer`? If so, I can't get it to work.

**Comment by slutske22** [comment]
> Sorry, I did a poor job of explaining my question.
> 
> How do I enable the `ignoreDeprecationWarning` option that is in esri-leaflet? Is it a prop for `BasemapLayer`? If so, I can't get it to work.

Passing it as a prop should work:

```ts
        <BasemapLayer
          ref={basemapLayerRef}
          name="DarkGray"
          // @ts-expect-error
          ignoreDeprecationWarning
        />
```

When I pass this prop in, the deprecation warning stops showing up in the console.  If you are using typescript, you'll see that `ignoreDeprecationWarning` is not officially a prop. This is because @types/esri-leaflet (currently v 2.1.9) has not added it as an official prop, at least yet:

<img width="626" alt="Screen Shot 2022-06-13 at 5 00 37 AM" src="https://user-images.githubusercontent.com/52637023/173383577-4a0c39cd-27ee-43f2-b6a1-fa813f48febe.png">

This just means that @types/esri-leaflet is not up to date with esri-leaflet.  Passing this as a prop seems to work fine for me.  What issue are you having?

**Comment by bobmoretti** [comment]
Sorry, that was the piece I was missing.

This is my lack of familiarity with React... I had the mistaken impression that props were always key/value pairs. I tried `ignoreDeprecationWarning={true}` and many other variations thereof to no avail.

Thanks so much for your help.
