### ISSUE TITLE
BasemapLayer is deprecated 

### ISSUE THREAD

**Issue by shakesBeardZ** [slutske22/react-esri-leaflet#17]
I'm getting error in VsCode indicating that BasemapLayer is deprecated and I should used ``L.esri.Vector...`` instead.

<img  src="https://user-images.githubusercontent.com/15571628/190903270-b08b1be8-172a-40a2-9ffd-edb42927733d.png" width="700" />

**Comment by slutske22** [comment]
This is intentional, as [L.esri.BasemapLayer is deprecated now](https://esri.github.io/esri-leaflet/api-reference/layers/basemap-layer.html).  You can read a bit more about how to supress the warning [here](https://github.com/slutske22/react-esri-leaflet/issues/14).
