### ISSUE TITLE
Could not resolve dependency: [ react-esri-leaflet , esri-leaflet , esri-leaflet-vector ]

### ISSUE THREAD

**Issue by technicallybo** [slutske22/react-esri-leaflet#3]
Have any of you run into this issue using your latest version? Wondering how you might have resolved it.

Some Context...
I have react, react-dom, leaflet, react-leaflet, esri-leaflet already installed (see below for all package.json list). Then when I try to install react-esri-leaflet I get some dependency errors (see below for error output in terminal).
For reference, I am using the basic Create React App setup.

--- Error when npm install react-esri-leaflet ---
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: hfm-cra@0.1.0
npm ERR! Found: esri-leaflet@3.0.1
npm ERR! node_modules/esri-leaflet
npm ERR!   esri-leaflet@"^3.0.1" from the root project
npm ERR!   peer esri-leaflet@"^3.0.1" from react-esri-leaflet@1.1.1
npm ERR!   node_modules/react-esri-leaflet
npm ERR!     react-esri-leaflet@"*" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer esri-leaflet@"^2.3.0" from esri-leaflet-vector@3.0.0
npm ERR! node_modules/esri-leaflet-vector
npm ERR!   peer esri-leaflet-vector@"^3.0.0" from react-esri-leaflet@1.1.1
npm ERR!   node_modules/react-esri-leaflet
npm ERR!     react-esri-leaflet@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

--- From my Package.json ---
"dependencies": {
    "@emotion/css": "^11.1.3",
    "@testing-library/jest-dom": "^5.11.4",
    "@testing-library/react": "^11.1.0",
    "@testing-library/user-event": "^12.1.10",
    "esri-leaflet": "^3.0.1",
    "leaflet": "^1.7.1",
    "lodash.every": "^4.6.0",
    "lodash.filter": "^4.6.0",
    "lodash.get": "^4.4.2",
    "lodash.has": "^4.5.2",
    "lodash.pick": "^4.4.0",
    "lodash.set": "^4.3.2",
    "lodash.unset": "^4.5.2",
    "mobx": "^6.3.0",
    "mobx-react-lite": "^3.2.0",
    "nanoid": "^3.1.22",
    "page": "^1.11.6",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-icons": "^4.2.0",
    "react-leaflet": "^3.1.0",
    "react-scripts": "4.0.3",
    "web-vitals": "^1.0.1"
}

**Comment by slutske22** [comment]
Are there actually any issues *using* the library, aside from the installation error you've listed?

I suspect this is actually an issue with esri-leaflet-vector, as the version of esri-leaflet listed in its package.json is ^2.3.0, but you've got ^3 in your project (as is required by the latest version of react-esri-leaflet).  I think they've got to change the peerDependency in that plugin's package.json from esri-leaflet ^2.3.0 to >2.3.0, so that anything above 2.3.0, including the 3x version you'd be using, can be resolved.

I've logged [an issue](https://github.com/Esri/esri-leaflet-vector/issues/82) in the esri-leaflet-vector repo, so we'll see what they say there.

**Comment by slutske22** [comment]
I tried this from scratch and I can't really reproduce this exact error.  Basically, I created a blank folder, `cd` into that folder, and initialize an npm package with `npm init -y`.  Then install `npm i react react-dom leaflet react-leaflet esri-leaflet`.  After that, I `npm i react-esri-leaflet`.  I get some peerDependency *warnings*:

```
slutske@LP-SLUTSKE-OSX Documents % npm i react-esri-leaflet
npm WARN saveError ENOENT: no such file or directory, open '/Users/slutske/Documents/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/slutske/Documents/package.json'
npm WARN react-esri-leaflet@1.1.1 requires a peer of esri-leaflet-cluster@^2.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-esri-leaflet@1.1.1 requires a peer of esri-leaflet-geocoder@^3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-esri-leaflet@1.1.1 requires a peer of esri-leaflet-heatmap@^2.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-esri-leaflet@1.1.1 requires a peer of esri-leaflet-vector@^3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-esri-leaflet@1.1.1 requires a peer of leaflet.heat@^0.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-esri-leaflet@1.1.1 requires a peer of leaflet.markercluster@^1.5.0 but none is installed. You must install peer dependencies yourself.
npm WARN Documents No description
npm WARN Documents No repository field.
npm WARN Documents No README data
npm WARN Documents No license field.

+ react-esri-leaflet@1.1.1
added 1 package from 1 contributor and audited 17 packages in 1.713s
found 0 vulnerabilities
```

But no *errors*.

I also tried initializing with CRA.  `npx create-react-app react-esri-leaflet-testing`.  In the project forlder that's created, `npm i leaflet react-leaflet esri-leaflet`.  Then `npm i react-esri-leaflet`. I get pretty much the same warning as above.  No errors though.

***Q***: What versions of node and npm are you working with?

**Comment by technicallybo** [comment]
Hmm, that is strange. Perhaps its something specific to my env creating an error rather than just a warning, but I have no great ideas as to why.

Below is the more verbose error log from my attempt to install the package a few mins ago (probably won't be of much more help, but whatevs). Note that I am using Node v16.0 and npm v7.10.

> Are there actually any issues using the library, aside from the installation error you've listed?

I have not been able to install the library. I opted to just use the underlying esri-leaflet pkg and build on top of it (I had to complete the story for a sprint deadline, so I stopped trying this package).

Since you can't reproduce the issue, maybe it is just something with my machine/env. Feel free to close this issue (or i can if you need me to). If I return to this package in the future and run into problems again, I will try to investigate further into my env; if I get something reproducible, I will open the ticket again and share.

Thanks for logging the issue with esri-leaflet-vector btw.


/Users/bo/.npm/_logs/2021-05-11T14_57_10_297Z-debug.log
> 0 verbose cli [
> 0 verbose cli   '/Users/bo/.nvm/versions/node/v16.0.0/bin/node',
> 0 verbose cli   '/Users/bo/.nvm/versions/node/v16.0.0/bin/npm',
> 0 verbose cli   'i',
> 0 verbose cli   'react-esri-leaflet'
> 0 verbose cli ]
> 1 info using npm@7.10.0
> 2 info using node@v16.0.0
> 3 timing npm:load:whichnode Completed in 1ms
> 4 timing config:load:defaults Completed in 2ms
> 5 timing config:load:file:/Users/bo/.nvm/versions/node/v16.0.0/lib/node_modules/npm/npmrc Completed in 1ms
> 6 timing config:load:builtin Completed in 1ms
> 7 timing config:load:cli Completed in 1ms
> 8 timing config:load:env Completed in 1ms
> 9 timing config:load:file:/Users/bo/Sites/hfm/.npmrc Completed in 2ms
> 10 timing config:load:project Completed in 2ms
> 11 timing config:load:file:/Users/bo/.npmrc Completed in 0ms
> 12 timing config:load:user Completed in 0ms
> 13 timing config:load:file:/Users/bo/.nvm/versions/node/v16.0.0/etc/npmrc Completed in 0ms
> 14 timing config:load:global Completed in 0ms
> 15 timing config:load:validate Completed in 1ms
> 16 timing config:load:setEnvs Completed in 0ms
> 17 timing config:load Completed in 8ms
> 18 timing npm:load:configload Completed in 8ms
> 19 timing npm:load:setTitle Completed in 16ms
> 20 timing npm:load:setupLog Completed in 2ms
> 21 timing npm:load:cleanupLog Completed in 1ms
> 22 timing npm:load:configScope Completed in 0ms
> 23 timing npm:load:projectScope Completed in 0ms
> 24 timing npm:load Completed in 29ms
> 25 timing config:load:flatten Completed in 2ms
> 26 timing arborist:ctor Completed in 0ms
> 27 timing idealTree:init Completed in 870ms
> 28 timing idealTree:userRequests Completed in 5ms
> 29 silly idealTree buildDeps
> 30 silly fetch manifest react-esri-leaflet@*
> 31 timing arborist:ctor Completed in 0ms
> 32 http fetch GET 304 https://registry.npmjs.org/react-esri-leaflet 1240ms (from cache)
> 33 silly fetch manifest esri-leaflet@^3.0.1
> 34 http fetch GET 200 https://registry.npmjs.org/esri-leaflet 3ms (from cache)
> 35 silly fetch manifest leaflet@^1.7.1
> 36 http fetch GET 200 https://registry.npmjs.org/leaflet 1ms (from cache)
> 37 silly fetch manifest esri-leaflet-cluster@^2.1.0
> 38 http fetch GET 304 https://registry.npmjs.org/esri-leaflet-cluster 533ms (from cache)
> 39 silly fetch manifest esri-leaflet-geocoder@^3.0.0
> 40 http fetch GET 304 https://registry.npmjs.org/esri-leaflet-geocoder 159ms (from cache)
> 41 silly fetch manifest esri-leaflet-heatmap@^2.0.0
> 42 http fetch GET 304 https://registry.npmjs.org/esri-leaflet-heatmap 450ms (from cache)
> 43 silly fetch manifest esri-leaflet-vector@^3.0.0
> 44 http fetch GET 304 https://registry.npmjs.org/esri-leaflet-vector 612ms (from cache)
> 45 timing idealTree Completed in 3892ms
> 46 timing command:install Completed in 3905ms
> 47 verbose stack Error: unable to resolve dependency tree
> 47 verbose stack     at Arborist.[failPeerConflict] (/Users/bo/.nvm/versions/node/v16.0.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1210:25)
> 47 verbose stack     at Arborist.[loadPeerSet] (/Users/bo/.nvm/versions/node/v16.0.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1203:30)
> 47 verbose stack     at Arborist.[nodeFromEdge] (/Users/bo/.nvm/versions/node/v16.0.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:986:30)
> 47 verbose stack     at async Arborist.[loadPeerSet] (/Users/bo/.nvm/versions/node/v16.0.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1163:11)
> 47 verbose stack     at async Arborist.[buildDepStep] (/Users/bo/.nvm/versions/node/v16.0.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:891:11)
> 47 verbose stack     at async Arborist.buildIdealTree (/Users/bo/.nvm/versions/node/v16.0.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:217:7)
> 47 verbose stack     at async Promise.all (index 1)
> 47 verbose stack     at async Arborist.reify (/Users/bo/.nvm/versions/node/v16.0.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:134:5)
> 47 verbose stack     at async Install.install (/Users/bo/.nvm/versions/node/v16.0.0/lib/node_modules/npm/lib/install.js:137:5)
> 48 verbose cwd /Users/bo/Sites/hfm
> 49 verbose Darwin 18.7.0
> 50 verbose argv "/Users/bo/.nvm/versions/node/v16.0.0/bin/node" "/Users/bo/.nvm/versions/node/v16.0.0/bin/npm" "i" "react-esri-leaflet"
> 51 verbose node v16.0.0
> 52 verbose npm  v7.10.0
> 53 error code ERESOLVE
> 54 error ERESOLVE unable to resolve dependency tree
> 55 error
> 56 error While resolving: [1mhfm-cra[22m@[1m0.1.0[22m
> 56 error Found: [1mesri-leaflet[22m@[1m3.0.1[22m[2m[22m
> 56 error [2mnode_modules/esri-leaflet[22m
> 56 error   [1mesri-leaflet[22m@"[1m^3.0.1[22m" from the root project
> 56 error   [35mpeer[39m [1mesri-leaflet[22m@"[1m^3.0.1[22m" from [1mreact-esri-leaflet[22m@[1m1.1.1[22m[2m[22m
> 56 error   [2mnode_modules/react-esri-leaflet[22m
> 56 error     [1mreact-esri-leaflet[22m@"[1m*[22m" from the root project
> 56 error
> 56 error Could not resolve dependency:
> 56 error [35mpeer[39m [1mesri-leaflet[22m@"[1m^2.3.0[22m" from [1mesri-leaflet-vector[22m@[1m3.0.0[22m[2m[22m
> 56 error [2mnode_modules/esri-leaflet-vector[22m
> 56 error   [35mpeer[39m [1mesri-leaflet-vector[22m@"[1m^3.0.0[22m" from [1mreact-esri-leaflet[22m@[1m1.1.1[22m[2m[22m
> 56 error   [2mnode_modules/react-esri-leaflet[22m
> 56 error     [1mreact-esri-leaflet[22m@"[1m*[22m" from the root project
> 56 error
> 56 error Fix the upstream dependency conflict, or retry
> 56 error this command with --force, or --legacy-peer-deps
> 56 error to accept an incorrect (and potentially broken) dependency resolution.
> 56 error
> 56 error See /Users/bo/.npm/eresolve-report.txt for a full report.
> 57 verbose exit 1

**Comment by slutske22** [comment]
Its very strange that you're getting this as an error.  I've been usung node 12 and npm 6, so perhaps npm 7 is treating peerDep warning as errors now?  If you want to use react-esri-leaflet in the meantime, I would follow npm's suggestion and use `--force` or `--legacy-peer-deps`, which is basically what this is - a peerDep that is legacy for esri-leaflet vector.  Maybe npm7 treats major version updates as errors, which I'm not sure I would agree with.

Did you not have the same issue after running `npm i esri-leaflet esri-leaflet-vector`?

**Comment by technicallybo** [comment]
I had not tried running that specific scenario.

Here is what happened when I ran a similar scenario.

Starting with my current package.json (includes esri-leaflet 3.0 already), here are the steps (in bold) I took and results:
**npm install esri-leaflet-vector** (produces error)
**npm uninstall esri-leaflet** (removed as expected)
**npm install esri-leaflet-vector** (successfully installs with "esri-leaflet-vector": "^3.0.0" in package.json)
**npm install esri-leaflet** (successfully installs with "esri-leaflet": "^2.5.3" in package.json ...not "^3.0.1")
**npm install react-esri-leaflet** (produces error, given the versions this was expected, right?)



--- the more verbose version of the same steps ---

**npm install esri-leaflet-vector** (produces error)
> 0 verbose cli [
> 0 verbose cli   '/Users/bo/.nvm/versions/node/v16.0.0/bin/node',
> 0 verbose cli   '/Users/bo/.nvm/versions/node/v16.0.0/bin/npm',
> 0 verbose cli   'i',
> 0 verbose cli   'esri-leaflet-vector'
> 0 verbose cli ]
> 1 info using npm@7.10.0
> 2 info using node@v16.0.0
> 3 timing npm:load:whichnode Completed in 1ms
> 4 timing config:load:defaults Completed in 1ms
> 5 timing config:load:file:/Users/bo/.nvm/versions/node/v16.0.0/lib/node_modules/npm/npmrc Completed in 2ms
> 6 timing config:load:builtin Completed in 2ms
> 7 timing config:load:cli Completed in 1ms
> 8 timing config:load:env Completed in 0ms
> 9 timing config:load:file:/Users/bo/Sites/hfm/.npmrc Completed in 1ms
> 10 timing config:load:project Completed in 2ms
> 11 timing config:load:file:/Users/bo/.npmrc Completed in 0ms
> 12 timing config:load:user Completed in 0ms
> 13 timing config:load:file:/Users/bo/.nvm/versions/node/v16.0.0/etc/npmrc Completed in 0ms
> 14 timing config:load:global Completed in 0ms
> 15 timing config:load:validate Completed in 1ms
> 16 timing config:load:setEnvs Completed in 1ms
> 17 timing config:load Completed in 8ms
> 18 timing npm:load:configload Completed in 8ms
> 19 timing npm:load:setTitle Completed in 16ms
> 20 timing npm:load:setupLog Completed in 2ms
> 21 timing npm:load:cleanupLog Completed in 1ms
> 22 timing npm:load:configScope Completed in 0ms
> 23 timing npm:load:projectScope Completed in 0ms
> 24 timing npm:load Completed in 29ms
> 25 timing config:load:flatten Completed in 3ms
> 26 timing arborist:ctor Completed in 1ms
> 27 timing idealTree:init Completed in 867ms
> 28 timing idealTree:userRequests Completed in 5ms
> 29 silly idealTree buildDeps
> 30 silly fetch manifest esri-leaflet-vector@*
> 31 timing arborist:ctor Completed in 0ms
> 32 http fetch GET 304 https://registry.npmjs.org/esri-leaflet-vector 1200ms (from cache)
> 33 silly fetch manifest esri-leaflet@^3.0.1
> 34 http fetch GET 304 https://registry.npmjs.org/esri-leaflet 241ms (from cache)
> 35 silly fetch manifest esri-leaflet@^2.3.0
> 36 silly fetch manifest leaflet@^1.7.1
> 37 http fetch GET 200 https://registry.npmjs.org/leaflet 71ms
> 38 timing idealTree Completed in 2395ms
> 39 timing command:install Completed in 2406ms
> 40 verbose stack Error: unable to resolve dependency tree
> 40 verbose stack     at Arborist.[failPeerConflict] (/Users/bo/.nvm/versions/node/v16.0.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1210:25)
> 40 verbose stack     at Arborist.[loadPeerSet] (/Users/bo/.nvm/versions/node/v16.0.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1187:34)
> 40 verbose stack     at async Arborist.[buildDepStep] (/Users/bo/.nvm/versions/node/v16.0.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:891:11)
> 40 verbose stack     at async Arborist.buildIdealTree (/Users/bo/.nvm/versions/node/v16.0.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:217:7)
> 40 verbose stack     at async Promise.all (index 1)
> 40 verbose stack     at async Arborist.reify (/Users/bo/.nvm/versions/node/v16.0.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:134:5)
> 40 verbose stack     at async Install.install (/Users/bo/.nvm/versions/node/v16.0.0/lib/node_modules/npm/lib/install.js:137:5)
> 41 verbose cwd /Users/bo/Sites/hfm
> 42 verbose Darwin 18.7.0
> 43 verbose argv "/Users/bo/.nvm/versions/node/v16.0.0/bin/node" "/Users/bo/.nvm/versions/node/v16.0.0/bin/npm" "i" "esri-leaflet-vector"
> 44 verbose node v16.0.0
> 45 verbose npm  v7.10.0
> 46 error code ERESOLVE
> 47 error ERESOLVE unable to resolve dependency tree
> 48 error
> 49 error While resolving: [1mhfm-cra[22m@[1m0.1.0[22m
> 49 error Found: [1mesri-leaflet[22m@[1m3.0.1[22m[2m[22m
> 49 error [2mnode_modules/esri-leaflet[22m
> 49 error   [1mesri-leaflet[22m@"[1m^3.0.1[22m" from the root project
> 49 error
> 49 error Could not resolve dependency:
> 49 error [35mpeer[39m [1mesri-leaflet[22m@"[1m^2.3.0[22m" from [1mesri-leaflet-vector[22m@[1m3.0.0[22m[2m[22m
> 49 error [2mnode_modules/esri-leaflet-vector[22m
> 49 error   [1mesri-leaflet-vector[22m@"[1m*[22m" from the root project
> 49 error
> 49 error Fix the upstream dependency conflict, or retry
> 49 error this command with --force, or --legacy-peer-deps
> 49 error to accept an incorrect (and potentially broken) dependency resolution.
> 49 error
> 49 error See /Users/bo/.npm/eresolve-report.txt for a full report.
> 50 verbose exit 1


**npm uninstall esri-leaflet** (removed as expected)

**npm install esri-leaflet-vector** (successfully installs with "esri-leaflet-vector": "^3.0.0" in package.json)

**npm install esri-leaflet** (successfully installs with "esri-leaflet": "^2.5.3" in package.json ...not "^3.0.1")

**npm install react-esri-leaflet**
> 0 verbose cli [
> 0 verbose cli   '/Users/bo/.nvm/versions/node/v16.0.0/bin/node',
> 0 verbose cli   '/Users/bo/.nvm/versions/node/v16.0.0/bin/npm',
> 0 verbose cli   'install',
> 0 verbose cli   'react-esri-leaflet'
> 0 verbose cli ]
> 1 info using npm@7.10.0
> 2 info using node@v16.0.0
> 3 timing npm:load:whichnode Completed in 1ms
> 4 timing config:load:defaults Completed in 2ms
> 5 timing config:load:file:/Users/bo/.nvm/versions/node/v16.0.0/lib/node_modules/npm/npmrc Completed in 0ms
> 6 timing config:load:builtin Completed in 0ms
> 7 timing config:load:cli Completed in 1ms
> 8 timing config:load:env Completed in 1ms
> 9 timing config:load:file:/Users/bo/Sites/hfm/.npmrc Completed in 1ms
> 10 timing config:load:project Completed in 1ms
> 11 timing config:load:file:/Users/bo/.npmrc Completed in 0ms
> 12 timing config:load:user Completed in 0ms
> 13 timing config:load:file:/Users/bo/.nvm/versions/node/v16.0.0/etc/npmrc Completed in 0ms
> 14 timing config:load:global Completed in 0ms
> 15 timing config:load:validate Completed in 1ms
> 16 timing config:load:setEnvs Completed in 0ms
> 17 timing config:load Completed in 6ms
> 18 timing npm:load:configload Completed in 6ms
> 19 timing npm:load:setTitle Completed in 17ms
> 20 timing npm:load:setupLog Completed in 1ms
> 21 timing npm:load:cleanupLog Completed in 2ms
> 22 timing npm:load:configScope Completed in 0ms
> 23 timing npm:load:projectScope Completed in 0ms
> 24 timing npm:load Completed in 27ms
> 25 timing config:load:flatten Completed in 2ms
> 26 timing arborist:ctor Completed in 1ms
> 27 timing idealTree:init Completed in 783ms
> 28 timing idealTree:userRequests Completed in 5ms
> 29 silly idealTree buildDeps
> 30 silly fetch manifest react-esri-leaflet@*
> 31 timing arborist:ctor Completed in 0ms
> 32 http fetch GET 304 https://registry.npmjs.org/react-esri-leaflet 1162ms (from cache)
> 33 silly fetch manifest esri-leaflet@^2.5.3
> 34 http fetch GET 304 https://registry.npmjs.org/esri-leaflet 108ms (from cache)
> 35 silly fetch manifest esri-leaflet@^3.0.1
> 36 silly fetch manifest leaflet@^1.7.1
> 37 http fetch GET 304 https://registry.npmjs.org/leaflet 44ms (from cache)
> 38 timing idealTree Completed in 2116ms
> 39 timing command:install Completed in 2128ms
> 40 verbose stack Error: unable to resolve dependency tree
> 40 verbose stack     at Arborist.[failPeerConflict] (/Users/bo/.nvm/versions/node/v16.0.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1210:25)
> 40 verbose stack     at Arborist.[loadPeerSet] (/Users/bo/.nvm/versions/node/v16.0.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1187:34)
> 40 verbose stack     at async Arborist.[buildDepStep] (/Users/bo/.nvm/versions/node/v16.0.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:891:11)
> 40 verbose stack     at async Arborist.buildIdealTree (/Users/bo/.nvm/versions/node/v16.0.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:217:7)
> 40 verbose stack     at async Promise.all (index 1)
> 40 verbose stack     at async Arborist.reify (/Users/bo/.nvm/versions/node/v16.0.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:134:5)
> 40 verbose stack     at async Install.install (/Users/bo/.nvm/versions/node/v16.0.0/lib/node_modules/npm/lib/install.js:137:5)
> 41 verbose cwd /Users/bo/Sites/hfm
> 42 verbose Darwin 18.7.0
> 43 verbose argv "/Users/bo/.nvm/versions/node/v16.0.0/bin/node" "/Users/bo/.nvm/versions/node/v16.0.0/bin/npm" "install" "react-esri-leaflet"
> 44 verbose node v16.0.0
> 45 verbose npm  v7.10.0
> 46 error code ERESOLVE
> 47 error ERESOLVE unable to resolve dependency tree
> 48 error
> 49 error While resolving: [1mhfm-cra[22m@[1m0.1.0[22m
> 49 error Found: [1mesri-leaflet[22m@[1m2.5.3[22m[2m[22m
> 49 error [2mnode_modules/esri-leaflet[22m
> 49 error   [1mesri-leaflet[22m@"[1m^2.5.3[22m" from the root project
> 49 error
> 49 error Could not resolve dependency:
> 49 error [35mpeer[39m [1mesri-leaflet[22m@"[1m^3.0.1[22m" from [1mreact-esri-leaflet[22m@[1m1.1.1[22m[2m[22m
> 49 error [2mnode_modules/react-esri-leaflet[22m
> 49 error   [1mreact-esri-leaflet[22m@"[1m*[22m" from the root project
> 49 error
> 49 error Fix the upstream dependency conflict, or retry
> 49 error this command with --force, or --legacy-peer-deps
> 49 error to accept an incorrect (and potentially broken) dependency resolution.
> 49 error
> 49 error See /Users/bo/.npm/eresolve-report.txt for a full report.
> 50 verbose exit 1

**Comment by slutske22** [comment]
I find that to be *super* strange.  If you uninstall esri-leaflet, how could esri-leaflet-vector *not* throw the error that it can't find peerDep esri-leaflet@^2.3.0 - there no esri-leaflet there at all!

I know you may already have moved past this in your actual work (major bummer, I love seeing my open source projects make it into real-world projects), but I would suggest one of the following:

- use the `--force or --legacy-peer-deps` tag when installing react-esri-leaflet.  I guarantee you it will not cause problems
- just use my source code!

Less ideal solutions for now:

- try downgrading node and or npm
- wait for esri-leaflet-vector to potential update the peerDependency to >2.3.0, which should solve any peerDep issues with esri-leaflet

Should you feel so inclined, I would also try the following fresh project instructions to see if you get a similar error:
- make a new directory and `cd` into it
- `npm init -y`
- `npm i leaflet esri-leaflet`
- `npm i esri-leaflet-vector`

If following those instructions produces the same problem, then the issue is definitely not with this plugin, but with how the new versions of node or npm treat legacy peer dependencies.  If those instructions do *not* cause the same problem, I'm all out of ideas.

**Comment by technicallybo** [comment]
I completed the steps you requested (repeated below) and the same error occurred. To further explore if it was a version issue, I downgraded/switched my node and npm versions. The package successfully installed after downgrading. I am including the steps and results here just to be complete, but it looks like the node/npm version may play a role in the success (or failure) of the packages. So I think you may be correct.

These steps failed at esri-leaflet-vector (before the downgrade)
> make a new directory and cd into it
> npm init -y
> npm i leaflet esri-leaflet
> npm i esri-leaflet-vector

**nvm use 12.6.0**
Node 16 -> Node 12.6.0

**npm install npm@6.0.0**
npm 7.10 -> npm 6

These steps succeeded at esri-leaflet-vector (after the downgrade)
> make a new directory and cd into it
> npm init -y
> npm i leaflet esri-leaflet
> npm i esri-leaflet-vector


Thanks!

**Comment by slutske22** [comment]
I think its dumb that the newer versions of node & npm consider legacy peer dependency issues a hard error, rather than a warning `¯\_(ツ)_/¯`

Thanks for thoroughly investigating this issue with me.
